### ISSUE TITLE
DECC Room Labels

### ISSUE THREAD

**Issue by fawcett** [geospatialem/conference-map#18]
Love the indoor map.  It would be useful to have room name labels for the indoor DECC map.

**Comment by geospatialem** [comment]
Hey @fawcett - I've actually got them in the title of the popup. It doesn't look the greatest though, can you think of a better way to display the room names?

<img width="589" alt="Popup screenshot with title highlighted" src="https://cloud.githubusercontent.com/assets/5023024/16786463/7935973e-485a-11e6-8406-2b581afccc3c.png">

**Comment by fawcett** [comment]
I was thinking that people might want fixed labels for the rooms, maybe on at zoom 17 or greater.  That would allow them to look at the whole floor and see all of the room names at the same time.  

Last time that I looked at it, I don't think that there was native poly labeling in Leaflet.  You could use leaflet.label, or just add label points.  If you think that it is worth while, I could play around with it too.

**Comment by geospatialem** [comment]
Ahhh, sorry, I didn't catch that you meant in the map initially. Great idea! 

I'll work on implementing it - I added leaflet.label to another map, and love it!
