### ISSUE TITLE
Add DECC layout information and/or add the leaflet-indoor plugin for the conference layout

### ISSUE THREAD

**Issue by geospatialem** [geospatialem/conference-map#5]
![image](https://cloud.githubusercontent.com/assets/5023024/5060770/e3d5b5f8-6d30-11e4-88ee-96df94cb1034.png)

**Comment by mmdolbow** [comment]
Found the floor plan at http://www.decc.org/cms/files/capacity-guide2015.pdf. Don't think I'll have time to pull that into the indoor plugin, but who would I ask about where sessions, exhibit hall, etc will be? I was thinking about just adding simple points to designate those areas for folks.

**Comment by geospatialem** [comment]
Points work for me! :+1: You can contact Gerry and/or Ryan, they will give the final sign-off on what will be placed where on-site. I think they have this squared away but if not, they should have the logistics very soon.

**Comment by mmdolbow** [comment]
Got a map printout and the preliminary program to start on this, but now: am I adding points to the deccLayout.geojson file? Or to the "main.geojson" file? I'm thinking I need at least 3 points for the skyway level and two for the ground level. (I would distinguish the level merely with a property of the point.)

**Comment by geospatialem** [comment]
Good question.... how about the **_main.geojson_** file since that's what is coming straight into the map? 

The deccLayout.geojson is just sitting there collecting dust. I had big dreams for it, but didn't have time to play around with it. Maybe next year... 

Thanks for working on this! :sunglasses:

**Comment by geospatialem** [comment]
See commits 09ec1e3aecf43a137448cc42dede09af70664337, 5dbdd34db41cd10fae306e61bca526a821a78329, b7d031f5cbaa238b1c11189b7125a2a2f964f028 for reference on the two floors (ground and skyway). Thanks @mmdolbow!
